//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson9_BaiKiemTraGiuaKi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tddKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tddKhoa()
        {
            this.tddSinhViens = new HashSet<tddSinhVien>();
        }
    
        public string TddMaKH { get; set; }
        public string TddTenKH { get; set; }
        public Nullable<bool> TddTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tddSinhVien> tddSinhViens { get; set; }
    }
}
