//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson9_BaiKiemTraGiuaKi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tddSinhVien
    {
        public string TddMaSV { get; set; }
        public string TddHoSV { get; set; }
        public string TddTenSV { get; set; }
        public Nullable<System.DateTime> TddNgaySinh { get; set; }
        public Nullable<bool> TddPhai { get; set; }
        public string TddPhone { get; set; }
        public string TddEmail { get; set; }
        public string TddMaKH { get; set; }
    
        public virtual tddKhoa tddKhoa { get; set; }
    }
}
